import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";

const robotoSans = Roboto({
  variable: "--font-roboto-sans", 
  subsets: ["latin"], 
  weight: "700"
});

export const metadata = {
  title: "My Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${robotoSans.variable} antialiased`} >
        <Header />
          <main className="p-8 gap-16 sm:p-20 min-h-screen font-[family-name:var(--font-roboto-sans)] mx-24">
            {children}
          </main>
        <Footer />
      </body>
    </html>
  );
}
